export enum InfraConfigEnum {
  MAILER_SMTP_URL = 'MAILER_SMTP_URL',
  MAILER_ADDRESS_FROM = 'MAILER_ADDRESS_FROM',

  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',

  GITHUB_CLIENT_ID = 'GITHUB_CLIENT_ID',
  GITHUB_CLIENT_SECRET = 'GITHUB_CLIENT_SECRET',

  MICROSOFT_CLIENT_ID = 'MICROSOFT_CLIENT_ID',
  MICROSOFT_CLIENT_SECRET = 'MICROSOFT_CLIENT_SECRET',

  OPENID_ISSUER_NAME = 'OPENID_ISSUER_NAME',
  OPENID_ISSUER_URL = 'OPENID_ISSUER_URL',
  OPENID_ISSUER_ICON_URL = 'OPENID_ISSUER_ICON_URL',
  OPENID_AUTHORIZATION_ENDPOINT = 'OPENID_AUTHORIZATION_ENDPOINT',
  OPENID_TOKEN_ENDPOINT = 'OPENID_TOKEN_ENDPOINT',
  OPENID_USERINFO_ENDPOINT = 'OPENID_USERINFO_ENDPOINT',
  OPENID_END_SESSION_ENDPOINT = 'OPENID_END_SESSION_ENDPOINT',
  OPENID_JWKS_URI = 'OPENID_JWKS_URI',
  OPENID_SCOPE = 'OPENID_SCOPE',
  OPENID_CALLBACK_URL = 'OPENID_CALLBACK_URL',
  OPENID_CLIENT_ID = 'OPENID_CLIENT_ID',
  OPENID_CLIENT_SECRET = 'OPENID_CLIENT_SECRET',

  VITE_ALLOWED_AUTH_PROVIDERS = 'VITE_ALLOWED_AUTH_PROVIDERS',
}

export enum InfraConfigEnumForClient {
  MAILER_SMTP_URL = 'MAILER_SMTP_URL',
  MAILER_ADDRESS_FROM = 'MAILER_ADDRESS_FROM',

  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',

  GITHUB_CLIENT_ID = 'GITHUB_CLIENT_ID',
  GITHUB_CLIENT_SECRET = 'GITHUB_CLIENT_SECRET',

  MICROSOFT_CLIENT_ID = 'MICROSOFT_CLIENT_ID',
  MICROSOFT_CLIENT_SECRET = 'MICROSOFT_CLIENT_SECRET',

  OPENID_ISSUER_NAME = 'OPENID_ISSUER_NAME',
  OPENID_ISSUER_URL = 'OPENID_ISSUER_URL',
  OPENID_ISSUER_ICON_URL = 'OPENID_ISSUER_ICON_URL',
  OPENID_AUTHORIZATION_ENDPOINT = 'OPENID_AUTHORIZATION_ENDPOINT',
  OPENID_TOKEN_ENDPOINT = 'OPENID_TOKEN_ENDPOINT',
  OPENID_USERINFO_ENDPOINT = 'OPENID_USERINFO_ENDPOINT',
  OPENID_END_SESSION_ENDPOINT = 'OPENID_END_SESSION_ENDPOINT',
  OPENID_JWKS_URI = 'OPENID_JWKS_URI',
  OPENID_SCOPE = 'OPENID_SCOPE',
  OPENID_CALLBACK_URL = 'OPENID_CALLBACK_URL',
  OPENID_CLIENT_ID = 'OPENID_CLIENT_ID',
  OPENID_CLIENT_SECRET = 'OPENID_CLIENT_SECRET',
}
