export enum InfraConfigEnum {
  MAILER_SMTP_URL = 'MAILER_SMTP_URL',
  MAILER_ADDRESS_FROM = 'MAILER_ADDRESS_FROM',

  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL',
  GOOGLE_SCOPE = 'GOOGLE_SCOPE',

  GITHUB_CLIENT_ID = 'GITHUB_CLIENT_ID',
  GITHUB_CLIENT_SECRET = 'GITHUB_CLIENT_SECRET',
  GITHUB_CALLBACK_URL = 'GITHUB_CALLBACK_URL',
  GITHUB_SCOPE = 'GITHUB_SCOPE',

  MICROSOFT_CLIENT_ID = 'MICROSOFT_CLIENT_ID',
  MICROSOFT_CLIENT_SECRET = 'MICROSOFT_CLIENT_SECRET',
  MICROSOFT_CALLBACK_URL = 'MICROSOFT_CALLBACK_URL',
  MICROSOFT_SCOPE = 'MICROSOFT_SCOPE',
  MICROSOFT_TENANT = 'MICROSOFT_TENANT',

  VITE_ALLOWED_AUTH_PROVIDERS = 'VITE_ALLOWED_AUTH_PROVIDERS',

  ALLOW_ANALYTICS_COLLECTION = 'ALLOW_ANALYTICS_COLLECTION',
  ANALYTICS_USER_ID = 'ANALYTICS_USER_ID',
  IS_FIRST_TIME_INFRA_SETUP = 'IS_FIRST_TIME_INFRA_SETUP',

  OPENID_ISSUER_NAME = 'OPENID_ISSUER_NAME',
  OPENID_ISSUER_URL = 'OPENID_ISSUER_URL',
  OPENID_ISSUER_ICON_URL = 'OPENID_ISSUER_ICON_URL',
  OPENID_AUTHORIZATION_ENDPOINT = 'OPENID_AUTHORIZATION_ENDPOINT',
  OPENID_TOKEN_ENDPOINT = 'OPENID_TOKEN_ENDPOINT',
  OPENID_USERINFO_ENDPOINT = 'OPENID_USERINFO_ENDPOINT',
  OPENID_END_SESSION_ENDPOINT = 'OPENID_END_SESSION_ENDPOINT',
  OPENID_JWKS_URI = 'OPENID_JWKS_URI',
  OPENID_SCOPE = 'OPENID_SCOPE',
  OPENID_CALLBACK_URL = 'OPENID_CALLBACK_URL',
  OPENID_CLIENT_ID = 'OPENID_CLIENT_ID',
  OPENID_CLIENT_SECRET = 'OPENID_CLIENT_SECRET',
}
